# -*- coding: utf-8 -*-
"""Copy of grok bot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZqogTo8Jw_17hHVoAZGsCfYCTbuigJ2t
"""

# ============================================
# STEP 1: Project Setup & Dependencies
# ============================================

# Install required libraries
!pip install -q python-telegram-bot==21.6
!pip install -q nest_asyncio

import nest_asyncio
nest_asyncio.apply()

import os
import sqlite3
import logging
import asyncio
import random
import string
from datetime import datetime, timezone
from typing import Optional, Dict, List, Tuple

from telegram import (
    Update,
    InlineKeyboardButton,
    InlineKeyboardMarkup,
    ReplyKeyboardMarkup,
    KeyboardButton,
    InputFile,
)
from telegram.ext import (
    Application,
    CommandHandler,
    CallbackQueryHandler,
    MessageHandler,
    ContextTypes,
    filters,
    ConversationHandler,
)
from telegram.constants import ParseMode
from telegram.error import BadRequest, Forbidden

# Logging
logging.basicConfig(
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    level=logging.INFO
)
logger = logging.getLogger(__name__)

print("✅ Step 1 completed successfully!")
print("Libraries installed and basic imports ready.")
print("\n➡️ Reply with 'next' to continue to Step 2 (Database Design & Initialization)")

# ============================================
# STEP 2: Database Design & Initialization
# ============================================

DB_NAME = "veltrix_store.db"

def init_db():
    conn = sqlite3.connect(DB_NAME)
    c = conn.cursor()

    # Users table
    c.execute('''
        CREATE TABLE IF NOT EXISTS users (
            user_id INTEGER PRIMARY KEY,
            username TEXT,
            full_name TEXT,
            balance REAL DEFAULT 0.0,
            total_spent REAL DEFAULT 0.0,
            total_orders INTEGER DEFAULT 0,
            joined_at TEXT,
            is_banned INTEGER DEFAULT 0,
            last_active TEXT
        )
    ''')

    # Products table
    c.execute('''
        CREATE TABLE IF NOT EXISTS products (
            product_id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL,
            duration TEXT,
            price REAL NOT NULL,
            emoji TEXT,
            is_active INTEGER DEFAULT 1
        )
    ''')

    # Stock table (each line = one account)
    c.execute('''
        CREATE TABLE IF NOT EXISTS stock (
            stock_id INTEGER PRIMARY KEY AUTOINCREMENT,
            product_id INTEGER,
            content TEXT NOT NULL,
            status TEXT DEFAULT 'AVAILABLE',  -- AVAILABLE, RESERVED, DELIVERED
            reserved_by INTEGER,
            reserved_at TEXT,
            delivered_at TEXT,
            order_id TEXT,
            FOREIGN KEY (product_id) REFERENCES products(product_id)
        )
    ''')

    # Orders table
    c.execute('''
        CREATE TABLE IF NOT EXISTS orders (
            order_id TEXT PRIMARY KEY,
            user_id INTEGER,
            product_id INTEGER,
            quantity INTEGER,
            total_amount REAL,
            payment_method TEXT,          -- wallet, bep20, binance
            status TEXT DEFAULT 'PENDING', -- PENDING, APPROVED, REJECTED, DELIVERED, CANCELLED
            txid TEXT,
            binance_ref TEXT,
            created_at TEXT,
            approved_at TEXT,
            delivered_at TEXT,
            admin_note TEXT,
            FOREIGN KEY (user_id) REFERENCES users(user_id),
            FOREIGN KEY (product_id) REFERENCES products(product_id)
        )
    ''')

    # Wallet deposits table
    c.execute('''
        CREATE TABLE IF NOT EXISTS wallet_deposits (
            deposit_id TEXT PRIMARY KEY,
            user_id INTEGER,
            amount REAL,
            payment_method TEXT,          -- bep20, binance
            status TEXT DEFAULT 'PENDING', -- PENDING, APPROVED, REJECTED
            txid TEXT,
            binance_ref TEXT,
            created_at TEXT,
            approved_at TEXT,
            admin_note TEXT,
            FOREIGN KEY (user_id) REFERENCES users(user_id)
        )
    ''')

    # Admin logs
    c.execute('''
        CREATE TABLE IF NOT EXISTS admin_logs (
            log_id INTEGER PRIMARY KEY AUTOINCREMENT,
            admin_id INTEGER,
            action TEXT,
            details TEXT,
            created_at TEXT
        )
    ''')

    # Settings table (for future use)
    c.execute('''
        CREATE TABLE IF NOT EXISTS settings (
            key TEXT PRIMARY KEY,
            value TEXT
        )
    ''')

    conn.commit()

    # Insert default products if they don't exist
    c.execute("SELECT COUNT(*) FROM products")
    if c.fetchone()[0] == 0:
        products = [
            ("Netflix 4K UHD", "1 Month", 1.00, "📺"),
            ("Spotify Premium", "2 Months", 0.60, "🎵"),
            ("YouTube Premium Invite", "1 Month", 0.30, "▶️"),
            ("Gemini Pro", "18 Months", 0.50, "✨"),
        ]
        c.executemany(
            "INSERT INTO products (name, duration, price, emoji) VALUES (?, ?, ?, ?)",
            products
        )
        conn.commit()
        print("✅ Default products inserted successfully")

    conn.close()
    print("✅ Database initialized successfully!")
    print("Tables created: users, products, stock, orders, wallet_deposits, admin_logs, settings")

# Run initialization
init_db()

print("\n➡️ Reply with 'next' to continue to Step 3 (Configuration & Constants)")

# ============================================
# STEP 3: Configuration & Constants
# ============================================

# ====================== CRITICAL SETTINGS ======================
ADMIN_ID = 6800369787                    # Only this user can access admin panel
FORCE_JOIN_CHANNEL = "@veltrixxstore"    # Mandatory channel
SUPPORT_USERNAME = "@sagaredtzz"

# Payment details
BEP20_ADDRESS = "0x99f30ec925ff5b997c582e8c9ac92ffe9093d9c8"
BINANCE_PAY_ID = "511225998"

# Store name
STORE_NAME = "Veltrix Store"

# ====================== BOT TOKEN (SAFE WAY) ======================
# In Google Colab we will load it from secrets later.
# For now we keep a placeholder.
BOT_TOKEN = None   # Will be set in Step 4

# ====================== CONVERSATION STATES ======================
(
    SELECT_QUANTITY,
    SELECT_PAYMENT_METHOD,
    WAITING_TXID,
    WAITING_BINANCE_REF,
    DEPOSIT_AMOUNT,
    DEPOSIT_PAYMENT_METHOD,
    DEPOSIT_WAITING_TXID,
    DEPOSIT_WAITING_BINANCE_REF,
    BROADCAST_MESSAGE,
    BROADCAST_CONFIRM,
    ADD_STOCK_PRODUCT,
    ADD_STOCK_FILE,
    CLEAR_STOCK_CONFIRM,
) = range(13)

# ====================== HELPER FUNCTIONS ======================

def generate_order_id() -> str:
    """Generate unique Order ID: VTX-YYYYMMDD-XXXXXX"""
    date_part = datetime.now(timezone.utc).strftime("%Y%m%d")
    random_part = ''.join(random.choices(string.ascii_uppercase + string.digits, k=6))
    return f"VTX-{date_part}-{random_part}"

def generate_deposit_id() -> str:
    """Generate unique Deposit ID"""
    date_part = datetime.now(timezone.utc).strftime("%Y%m%d")
    random_part = ''.join(random.choices(string.ascii_uppercase + string.digits, k=6))
    return f"DEP-{date_part}-{random_part}"

def get_db_connection():
    conn = sqlite3.connect(DB_NAME)
    conn.row_factory = sqlite3.Row
    return conn

def is_admin(user_id: int) -> bool:
    return user_id == ADMIN_ID

def format_money(amount: float) -> str:
    return f"${amount:.2f}"

def get_current_time() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

print("✅ Step 3 completed successfully!")
print(f"Admin ID        : {ADMIN_ID}")
print(f"Force Join      : {FORCE_JOIN_CHANNEL}")
print(f"BEP20 Address   : {BEP20_ADDRESS}")
print(f"Binance Pay ID  : {BINANCE_PAY_ID}")
print(f"Support         : {SUPPORT_USERNAME}")
print("\n➡️ Reply with 'next' to continue to Step 4 (Bot Token + Application Setup)")

# ============================================
# STEP 4: Bot Token + Application Setup
# ============================================

# ---------- SAFE TOKEN LOADING ----------
# Method 1 (Recommended): Use Colab Secrets
# 1. Click the key icon (Secrets) on the left sidebar in Colab
# 2. Add a new secret named: BOT_TOKEN
# 3. Paste your real BotFather token as the value
# 4. Enable "Notebook access"

try:
    from google.colab import userdata
    BOT_TOKEN = userdata.get('BOT_TOKEN')
    print("✅ Bot Token loaded successfully from Colab Secrets")
except Exception as e:
    print("⚠️ Could not load from Colab Secrets.")
    print("You can temporarily paste the token below (not recommended for long-term).")
    # BOT_TOKEN = "PASTE_YOUR_TOKEN_HERE"   # ← Uncomment only if needed
    raise Exception("Please add BOT_TOKEN in Colab Secrets and try again.")

if not BOT_TOKEN:
    raise Exception("BOT_TOKEN is empty! Please set it in Colab Secrets.")

# ---------- CREATE APPLICATION ----------
application = Application.builder().token(BOT_TOKEN).build()

print("✅ Telegram Application created successfully!")
print("Bot is ready to receive handlers.")
print("\n➡️ Reply with 'next' to continue to Step 5 (Force Join + Membership Check)")

# ============================================
# STEP 5: Force Join + Membership Check
# ============================================

async def check_membership(user_id: int, context: ContextTypes.DEFAULT_TYPE) -> bool:
    """Check if user is member of the force-join channel"""
    try:
        member = await context.bot.get_chat_member(
            chat_id=FORCE_JOIN_CHANNEL,
            user_id=user_id
        )
        return member.status in ["member", "administrator", "creator"]
    except Exception as e:
        logger.error(f"Membership check error for {user_id}: {e}")
        return False


async def force_join_message(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Send the force-join screen"""
    keyboard = [
        [InlineKeyboardButton("📢 Join Channel", url=f"https://t.me/{FORCE_JOIN_CHANNEL.replace('@', '')}")],
        [InlineKeyboardButton("✅ Check Membership", callback_data="check_membership")]
    ]
    reply_markup = InlineKeyboardMarkup(keyboard)

    text = (
        f"🔒 <b>Channel Membership Required</b>\n\n"
        f"Welcome to <b>{STORE_NAME}</b>!\n\n"
        f"To use this store you must join our official channel first:\n"
        f"<b>{FORCE_JOIN_CHANNEL}</b>\n\n"
        f"1️⃣ Click <b>Join Channel</b>\n"
        f"2️⃣ After joining, click <b>✅ Check Membership</b>"
    )

    if update.callback_query:
        await update.callback_query.edit_message_text(
            text=text,
            reply_markup=reply_markup,
            parse_mode=ParseMode.HTML
        )
    else:
        await update.message.reply_text(
            text=text,
            reply_markup=reply_markup,
            parse_mode=ParseMode.HTML
        )


async def check_membership_callback(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Handle the Check Membership button"""
    query = update.callback_query
    await query.answer()

    user_id = query.from_user.id
    is_member = await check_membership(user_id, context)

    if is_member:
        # Register / update user in database
        conn = get_db_connection()
        c = conn.cursor()
        c.execute("SELECT user_id FROM users WHERE user_id = ?", (user_id,))
        if not c.fetchone():
            c.execute(
                "INSERT INTO users (user_id, username, full_name, joined_at, last_active) VALUES (?, ?, ?, ?, ?)",
                (
                    user_id,
                    query.from_user.username,
                    query.from_user.full_name,
                    get_current_time(),
                    get_current_time()
                )
            )
        else:
            c.execute(
                "UPDATE users SET username = ?, full_name = ?, last_active = ? WHERE user_id = ?",
                (query.from_user.username, query.from_user.full_name, get_current_time(), user_id)
            )
        conn.commit()
        conn.close()

        await query.edit_message_text(
            text="✅ <b>Membership verified!</b>\n\nWelcome to the store.",
            parse_mode=ParseMode.HTML
        )
        # Show Main Menu
        await show_main_menu(update, context)
    else:
        await query.answer("❌ You haven't joined the channel yet!", show_alert=True)
        await force_join_message(update, context)


async def start_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """ /start command """
    user_id = update.effective_user.id

    # Always check membership first
    is_member = await check_membership(user_id, context)

    if not is_member:
        await force_join_message(update, context)
        return

    # Register user if new
    conn = get_db_connection()
    c = conn.cursor()
    c.execute("SELECT user_id FROM users WHERE user_id = ?", (user_id,))
    if not c.fetchone():
        c.execute(
            "INSERT INTO users (user_id, username, full_name, joined_at, last_active) VALUES (?, ?, ?, ?, ?)",
            (
                user_id,
                update.effective_user.username,
                update.effective_user.full_name,
                get_current_time(),
                get_current_time()
            )
        )
        conn.commit()
    else:
        c.execute(
            "UPDATE users SET last_active = ? WHERE user_id = ?",
            (get_current_time(), user_id)
        )
        conn.commit()
    conn.close()

    await show_main_menu(update, context)


# Placeholder for Main Menu (will be fully built in next step)
async def show_main_menu(update: Update, context: ContextTypes.DEFAULT_TYPE):
    text = (
        f"🏠 <b>Welcome to {STORE_NAME}</b>\n\n"
        f"Please choose an option from the menu below:"
    )
    keyboard = [
        [InlineKeyboardButton("🛍️ Shop Products", callback_data="shop")],
        [
            InlineKeyboardButton("👤 Profile", callback_data="profile"),
            InlineKeyboardButton("💰 Wallet", callback_data="wallet")
        ],
        [
            InlineKeyboardButton("📦 My Orders", callback_data="my_orders"),
            InlineKeyboardButton("🎧 Support", callback_data="support")
        ],
        [InlineKeyboardButton("📜 Terms & Info", callback_data="terms")]
    ]
    reply_markup = InlineKeyboardMarkup(keyboard)

    if update.callback_query:
        await update.callback_query.edit_message_text(
            text=text,
            reply_markup=reply_markup,
            parse_mode=ParseMode.HTML
        )
    else:
        await update.message.reply_text(
            text=text,
            reply_markup=reply_markup,
            parse_mode=ParseMode.HTML
        )


print("✅ Step 5 completed successfully!")
print("Force-join system + membership check ready.")
print("\n➡️ Reply with 'next' to continue to Step 6 (Main Menu + Basic Navigation)")

# ============================================
# STEP 6: Main Menu + Basic Navigation
# ============================================

async def show_main_menu(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Display the main menu"""
    user = update.effective_user
    text = (
        f"🏠 <b>Welcome to {STORE_NAME}</b>\n\n"
        f"Hello <b>{user.first_name}</b>!\n"
        f"Choose an option below:"
    )
    keyboard = [
        [InlineKeyboardButton("🛍️ Shop Products", callback_data="shop")],
        [
            InlineKeyboardButton("👤 Profile", callback_data="profile"),
            InlineKeyboardButton("💰 Wallet", callback_data="wallet")
        ],
        [
            InlineKeyboardButton("📦 My Orders", callback_data="my_orders"),
            InlineKeyboardButton("🎧 Support", callback_data="support")
        ],
        [InlineKeyboardButton("📜 Terms & Info", callback_data="terms")]
    ]
    reply_markup = InlineKeyboardMarkup(keyboard)

    if update.callback_query:
        await update.callback_query.edit_message_text(
            text=text,
            reply_markup=reply_markup,
            parse_mode=ParseMode.HTML
        )
        await update.callback_query.answer()
    else:
        await update.message.reply_text(
            text=text,
            reply_markup=reply_markup,
            parse_mode=ParseMode.HTML
        )


async def profile_handler(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Show user profile"""
    query = update.callback_query
    await query.answer()
    user_id = query.from_user.id

    conn = get_db_connection()
    c = conn.cursor()
    c.execute("SELECT * FROM users WHERE user_id = ?", (user_id,))
    user = c.fetchone()
    conn.close()

    if not user:
        await query.edit_message_text("❌ User not found. Please /start again.")
        return

    text = (
        f"👤 <b>Your Profile</b>\n\n"
        f"🆔 User ID: <code>{user['user_id']}</code>\n"
        f"👤 Name: <b>{user['full_name'] or 'N/A'}</b>\n"
        f"🔗 Username: @{user['username'] or 'None'}\n\n"
        f"💰 Balance: <b>{format_money(user['balance'])}</b>\n"
        f"🛒 Total Spent: <b>{format_money(user['total_spent'])}</b>\n"
        f"📦 Total Orders: <b>{user['total_orders']}</b>\n"
        f"📅 Joined: <b>{user['joined_at']}</b>"
    )

    keyboard = [[InlineKeyboardButton("🔙 Back to Menu", callback_data="main_menu")]]
    await query.edit_message_text(
        text=text,
        reply_markup=InlineKeyboardMarkup(keyboard),
        parse_mode=ParseMode.HTML
    )


async def support_handler(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Support button"""
    query = update.callback_query
    await query.answer()

    text = (
        f"🎧 <b>Support</b>\n\n"
        f"Need help? Contact our support:\n\n"
        f"👤 {SUPPORT_USERNAME}\n\n"
        f"Please include your <b>Order ID</b> if you have any issue with an order."
    )
    keyboard = [
        [InlineKeyboardButton("📩 Contact Support", url=f"https://t.me/{SUPPORT_USERNAME.replace('@', '')}")],
        [InlineKeyboardButton("🔙 Back to Menu", callback_data="main_menu")]
    ]
    await query.edit_message_text(
        text=text,
        reply_markup=InlineKeyboardMarkup(keyboard),
        parse_mode=ParseMode.HTML
    )


async def terms_handler(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Terms & Info"""
    query = update.callback_query
    await query.answer()

    text = (
        f"📜 <b>Terms & Information</b>\n\n"
        f"• All products are digital and delivered instantly after payment approval.\n"
        f"• Payments are manual (BEP20 / Binance Pay).\n"
        f"• No refunds after the product has been delivered.\n"
        f"• Do not share your accounts.\n"
        f"• Duplicate delivery is strictly prevented by our system.\n"
        f"• Support: {SUPPORT_USERNAME}\n\n"
        f"<b>{STORE_NAME}</b> – Quality digital products."
    )
    keyboard = [[InlineKeyboardButton("🔙 Back to Menu", callback_data="main_menu")]]
    await query.edit_message_text(
        text=text,
        reply_markup=InlineKeyboardMarkup(keyboard),
        parse_mode=ParseMode.HTML
    )


async def main_menu_callback(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Handle Back to Main Menu"""
    query = update.callback_query
    await query.answer()
    await show_main_menu(update, context)


print("✅ Step 6 completed successfully!")
print("Main Menu + Profile + Support + Terms ready.")
print("\n➡️ Reply with 'next' to continue to Step 7 (Shop Products + Quantity Selection)")

# ============================================
# STEP 7: Shop Products + Quantity Selection
# ============================================

async def shop_handler(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Show all available products"""
    query = update.callback_query
    await query.answer()

    conn = get_db_connection()
    c = conn.cursor()
    c.execute("SELECT * FROM products WHERE is_active = 1 ORDER BY product_id")
    products = c.fetchall()
    conn.close()

    if not products:
        text = "❌ No products available at the moment."
        keyboard = [[InlineKeyboardButton("🔙 Back to Menu", callback_data="main_menu")]]
        await query.edit_message_text(text=text, reply_markup=InlineKeyboardMarkup(keyboard))
        return

    text = f"🛍️ <b>Shop Products</b>\n\nSelect a product:"
    keyboard = []

    for p in products:
        # Count available stock
        conn = get_db_connection()
        c = conn.cursor()
        c.execute(
            "SELECT COUNT(*) FROM stock WHERE product_id = ? AND status = 'AVAILABLE'",
            (p['product_id'],)
        )
        stock_count = c.fetchone()[0]
        conn.close()

        btn_text = f"{p['emoji']} {p['name']} ({p['duration']}) — {format_money(p['price'])}"
        if stock_count == 0:
            btn_text += "  [Out of Stock]"

        keyboard.append([
            InlineKeyboardButton(
                btn_text,
                callback_data=f"product_{p['product_id']}"
            )
        ])

    keyboard.append([InlineKeyboardButton("🔙 Back to Menu", callback_data="main_menu")])

    await query.edit_message_text(
        text=text,
        reply_markup=InlineKeyboardMarkup(keyboard),
        parse_mode=ParseMode.HTML
    )


async def product_selected(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """User selected a product → ask for quantity"""
    query = update.callback_query
    await query.answer()

    product_id = int(query.data.split("_")[1])

    conn = get_db_connection()
    c = conn.cursor()
    c.execute("SELECT * FROM products WHERE product_id = ?", (product_id,))
    product = c.fetchone()

    c.execute(
        "SELECT COUNT(*) FROM stock WHERE product_id = ? AND status = 'AVAILABLE'",
        (product_id,)
    )
    stock_count = c.fetchone()[0]
    conn.close()

    if not product:
        await query.edit_message_text("❌ Product not found.")
        return

    if stock_count == 0:
        text = (
            f"{product['emoji']} <b>{product['name']}</b>\n\n"
            f"❌ <b>Out of Stock</b>\n\n"
            f"Please check back later."
        )
        keyboard = [
            [InlineKeyboardButton("🛍️ Back to Shop", callback_data="shop")],
            [InlineKeyboardButton("🔙 Main Menu", callback_data="main_menu")]
        ]
        await query.edit_message_text(
            text=text,
            reply_markup=InlineKeyboardMarkup(keyboard),
            parse_mode=ParseMode.HTML
        )
        return

    # Save selected product in context
    context.user_data['selected_product_id'] = product_id
    context.user_data['selected_product'] = dict(product)

    text = (
        f"{product['emoji']} <b>{product['name']}</b>\n"
        f"⏱ Duration: <b>{product['duration']}</b>\n"
        f"💵 Price: <b>{format_money(product['price'])}</b> each\n"
        f"📦 Available Stock: <b>{stock_count}</b>\n\n"
        f"Please select quantity:"
    )

    # Quantity buttons (1 to 5, or up to available stock)
    max_qty = min(5, stock_count)
    keyboard = []
    row = []
    for i in range(1, max_qty + 1):
        row.append(InlineKeyboardButton(str(i), callback_data=f"qty_{i}"))
        if len(row) == 3:
            keyboard.append(row)
            row = []
    if row:
        keyboard.append(row)

    keyboard.append([InlineKeyboardButton("🔙 Back to Shop", callback_data="shop")])

    await query.edit_message_text(
        text=text,
        reply_markup=InlineKeyboardMarkup(keyboard),
        parse_mode=ParseMode.HTML
    )


async def quantity_selected(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """User selected quantity → show payment methods"""
    query = update.callback_query
    await query.answer()

    qty = int(query.data.split("_")[1])
    product = context.user_data.get('selected_product')

    if not product:
        await query.edit_message_text("❌ Session expired. Please start again.")
        return

    total = product['price'] * qty

    context.user_data['quantity'] = qty
    context.user_data['total_amount'] = total

    text = (
        f"🛒 <b>Order Summary</b>\n\n"
        f"{product['emoji']} <b>{product['name']}</b>\n"
        f"⏱ Duration: {product['duration']}\n"
        f"📦 Quantity: <b>{qty}</b>\n"
        f"💵 Price each: {format_money(product['price'])}\n"
        f"💰 <b>Total: {format_money(total)}</b>\n\n"
        f"Select payment method:"
    )

    keyboard = [
        [InlineKeyboardButton("💰 Pay from Wallet", callback_data="pay_wallet")],
        [InlineKeyboardButton("🪙 Pay with BEP20", callback_data="pay_bep20")],
        [InlineKeyboardButton("🔵 Pay with Binance Pay", callback_data="pay_binance")],
        [InlineKeyboardButton("🔙 Back", callback_data=f"product_{product['product_id']}")]
    ]

    await query.edit_message_text(
        text=text,
        reply_markup=InlineKeyboardMarkup(keyboard),
        parse_mode=ParseMode.HTML
    )


print("✅ Step 7 completed successfully!")
print("Shop + Product selection + Quantity selection ready.")
print("\n➡️ Reply with 'next' to continue to Step 8 (Payment Methods – Wallet / BEP20 / Binance)")

# ============================================
# STEP 8: Payment Methods (Wallet / BEP20 / Binance) + YouTube Special Message
# ============================================

async def send_youtube_instruction(context: ContextTypes.DEFAULT_TYPE, order_id: str, user_id: int):
    """Send special message for YouTube Premium"""
    text = (
        f"✅ <b>YouTube Premium – Payment Successful!</b>\n\n"
        f"🆔 Order ID: <code>{order_id}</code>\n\n"
        f"Please send your <b>Gmail ID only</b> to this bot:\n\n"
        f"👉 <b>@veltrixstoreyoutube_bot</b>"
    )
    await context.bot.send_message(
        chat_id=user_id,
        text=text,
        parse_mode=ParseMode.HTML
    )


async def pay_from_wallet(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Pay using wallet balance (instant)"""
    query = update.callback_query
    await query.answer()

    user_id = query.from_user.id
    product = context.user_data.get('selected_product')
    qty = context.user_data.get('quantity')
    total = context.user_data.get('total_amount')

    if not product or not qty or total is None:
        await query.edit_message_text("❌ Session expired. Please start again from Shop.")
        return

    conn = get_db_connection()
    c = conn.cursor()

    # Check balance
    c.execute("SELECT balance FROM users WHERE user_id = ?", (user_id,))
    row = c.fetchone()
    balance = row['balance'] if row else 0.0

    if balance < total:
        conn.close()
        text = (
            f"❌ <b>Insufficient Balance</b>\n\n"
            f"Your balance: <b>{format_money(balance)}</b>\n"
            f"Required: <b>{format_money(total)}</b>\n\n"
            f"Please deposit first."
        )
        keyboard = [
            [InlineKeyboardButton("💰 Go to Wallet", callback_data="wallet")],
            [InlineKeyboardButton("🔙 Back", callback_data="shop")]
        ]
        await query.edit_message_text(text=text, reply_markup=InlineKeyboardMarkup(keyboard), parse_mode=ParseMode.HTML)
        return

    # Check available stock
    c.execute(
        "SELECT COUNT(*) FROM stock WHERE product_id = ? AND status = 'AVAILABLE'",
        (product['product_id'],)
    )
    available = c.fetchone()[0]
    if available < qty:
        conn.close()
        await query.edit_message_text("❌ Not enough stock left. Please try again.")
        return

    # Create unique Order ID
    order_id = generate_order_id()

    # Deduct balance
    c.execute(
        "UPDATE users SET balance = balance - ?, total_spent = total_spent + ?, total_orders = total_orders + 1 WHERE user_id = ?",
        (total, total, user_id)
    )

    # Create order
    c.execute('''
        INSERT INTO orders (order_id, user_id, product_id, quantity, total_amount, payment_method, status, created_at)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?)
    ''', (order_id, user_id, product['product_id'], qty, total, "wallet", "APPROVED", get_current_time()))

    # Reserve stock
    c.execute('''
        SELECT stock_id, content FROM stock
        WHERE product_id = ? AND status = 'AVAILABLE'
        LIMIT ?
    ''', (product['product_id'], qty))
    stocks = c.fetchall()

    delivered_items = []
    for stock in stocks:
        c.execute('''
            UPDATE stock SET status = 'DELIVERED', reserved_by = ?, delivered_at = ?, order_id = ?
            WHERE stock_id = ?
        ''', (user_id, get_current_time(), order_id, stock['stock_id']))
        delivered_items.append(stock['content'])

    conn.commit()
    conn.close()

    # ========== DELIVERY LOGIC ==========
    if "YouTube" in product['name']:
        # Special message for YouTube Premium
        await send_youtube_instruction(context, order_id, user_id)
        await query.edit_message_text(
            f"✅ <b>Payment Successful!</b>\n\nPlease check the message below.",
            parse_mode=ParseMode.HTML
        )
    else:
        # Normal delivery for other products
        delivery_text = (
            f"✅ <b>Payment Successful!</b>\n\n"
            f"🆔 Order ID: <code>{order_id}</code>\n"
            f"{product['emoji']} <b>{product['name']}</b>\n"
            f"📦 Quantity: {qty}\n"
            f"💰 Paid: {format_money(total)} (from Wallet)\n\n"
            f"<b>Your Product(s):</b>\n\n"
        )
        for i, item in enumerate(delivered_items, 1):
            delivery_text += f"<b>#{i}</b>\n<code>{item}</code>\n\n"

        delivery_text += "⚠️ Keep this information safe!"

        keyboard = [
            [InlineKeyboardButton("📦 My Orders", callback_data="my_orders")],
            [InlineKeyboardButton("🏠 Main Menu", callback_data="main_menu")]
        ]
        await query.edit_message_text(
            text=delivery_text,
            reply_markup=InlineKeyboardMarkup(keyboard),
            parse_mode=ParseMode.HTML
        )

    context.user_data.clear()


async def pay_bep20(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Start BEP20 payment flow"""
    query = update.callback_query
    await query.answer()

    product = context.user_data.get('selected_product')
    qty = context.user_data.get('quantity')
    total = context.user_data.get('total_amount')

    if not product or not qty or total is None:
        await query.edit_message_text("❌ Session expired. Please start again.")
        return

    order_id = generate_order_id()
    context.user_data['pending_order_id'] = order_id
    context.user_data['payment_method'] = "bep20"

    # Create pending order
    conn = get_db_connection()
    c = conn.cursor()
    c.execute('''
        INSERT INTO orders (order_id, user_id, product_id, quantity, total_amount, payment_method, status, created_at)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?)
    ''', (order_id, query.from_user.id, product['product_id'], qty, total, "bep20", "PENDING", get_current_time()))
    conn.commit()
    conn.close()

    text = (
        f"🪙 <b>BEP20 Payment</b>\n\n"
        f"🆔 Order ID: <code>{order_id}</code>\n"
        f"{product['emoji']} {product['name']} × {qty}\n"
        f"💰 Amount to pay: <b>{format_money(total)} USDT</b>\n\n"
        f"<b>Send exactly the amount to this address:</b>\n"
        f"<code>{BEP20_ADDRESS}</code>\n\n"
        f"Network: <b>BEP20 (BSC)</b>\n\n"
        f"After payment, click the button below and submit your Transaction ID (TXID)."
    )

    keyboard = [
        [InlineKeyboardButton("✅ I Have Paid – Submit TXID", callback_data="submit_txid")],
        [InlineKeyboardButton("❌ Cancel Order", callback_data=f"cancel_order_{order_id}")],
        [InlineKeyboardButton("🔙 Back", callback_data="shop")]
    ]

    await query.edit_message_text(
        text=text,
        reply_markup=InlineKeyboardMarkup(keyboard),
        parse_mode=ParseMode.HTML
    )


async def pay_binance(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Start Binance Pay flow"""
    query = update.callback_query
    await query.answer()

    product = context.user_data.get('selected_product')
    qty = context.user_data.get('quantity')
    total = context.user_data.get('total_amount')

    if not product or not qty or total is None:
        await query.edit_message_text("❌ Session expired. Please start again.")
        return

    order_id = generate_order_id()
    context.user_data['pending_order_id'] = order_id
    context.user_data['payment_method'] = "binance"

    conn = get_db_connection()
    c = conn.cursor()
    c.execute('''
        INSERT INTO orders (order_id, user_id, product_id, quantity, total_amount, payment_method, status, created_at)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?)
    ''', (order_id, query.from_user.id, product['product_id'], qty, total, "binance", "PENDING", get_current_time()))
    conn.commit()
    conn.close()

    text = (
        f"🔵 <b>Binance Pay</b>\n\n"
        f"🆔 Order ID: <code>{order_id}</code>\n"
        f"{product['emoji']} {product['name']} × {qty}\n"
        f"💰 Amount to pay: <b>{format_money(total)}</b>\n\n"
        f"<b>Pay to Binance ID:</b>\n"
        f"<code>{BINANCE_PAY_ID}</code>\n\n"
        f"After payment, click the button below and submit your Binance Payment Reference / Order ID."
    )

    keyboard = [
        [InlineKeyboardButton("✅ I Have Paid – Submit Reference", callback_data="submit_binance_ref")],
        [InlineKeyboardButton("❌ Cancel Order", callback_data=f"cancel_order_{order_id}")],
        [InlineKeyboardButton("🔙 Back", callback_data="shop")]
    ]

    await query.edit_message_text(
        text=text,
        reply_markup=InlineKeyboardMarkup(keyboard),
        parse_mode=ParseMode.HTML
    )


print("✅ Step 8 completed successfully!")
print("Wallet instant payment + BEP20 + Binance Pay + YouTube special message ready.")

# ============================================
# STEP 9: Submit TXID / Binance Reference + Cancel Order + Duplicate Protection
# ============================================

async def ask_txid(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Ask user to send TXID"""
    query = update.callback_query
    await query.answer()

    order_id = context.user_data.get('pending_order_id')
    if not order_id:
        await query.edit_message_text("❌ Session expired. Please start a new order.")
        return

    context.user_data['waiting_for'] = "txid"

    text = (
        f"📝 <b>Submit Transaction ID (TXID)</b>\n\n"
        f"🆔 Order ID: <code>{order_id}</code>\n\n"
        f"Please send your <b>BEP20 Transaction ID (TXID)</b> now.\n\n"
        f"Example:\n<code>0xabc123def456...</code>"
    )
    keyboard = [[InlineKeyboardButton("❌ Cancel Order", callback_data=f"cancel_order_{order_id}")]]

    await query.edit_message_text(
        text=text,
        reply_markup=InlineKeyboardMarkup(keyboard),
        parse_mode=ParseMode.HTML
    )


async def ask_binance_ref(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Ask user to send Binance reference"""
    query = update.callback_query
    await query.answer()

    order_id = context.user_data.get('pending_order_id')
    if not order_id:
        await query.edit_message_text("❌ Session expired. Please start a new order.")
        return

    context.user_data['waiting_for'] = "binance_ref"

    text = (
        f"📝 <b>Submit Binance Payment Reference</b>\n\n"
        f"🆔 Order ID: <code>{order_id}</code>\n\n"
        f"Please send your <b>Binance Pay Order ID / Payment Reference</b> now."
    )
    keyboard = [[InlineKeyboardButton("❌ Cancel Order", callback_data=f"cancel_order_{order_id}")]]

    await query.edit_message_text(
        text=text,
        reply_markup=InlineKeyboardMarkup(keyboard),
        parse_mode=ParseMode.HTML
    )


async def handle_payment_proof(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Receive TXID or Binance reference + Full Duplicate Protection"""
    if not update.message or not update.message.text:
        return

    user_id = update.effective_user.id
    proof = update.message.text.strip()
    waiting_for = context.user_data.get('waiting_for')
    order_id = context.user_data.get('pending_order_id')

    if not waiting_for or not order_id:
        return

    # Basic length validation
    if len(proof) < 8:
        await update.message.reply_text(
            "❌ Invalid payment proof.\nPlease send a valid TXID or Binance reference."
        )
        return

    conn = get_db_connection()
    c = conn.cursor()

    # 1. Check if order exists, belongs to user, and is still PENDING
    c.execute(
        "SELECT * FROM orders WHERE order_id = ? AND user_id = ? AND status = 'PENDING'",
        (order_id, user_id)
    )
    order = c.fetchone()

    if not order:
        conn.close()
        await update.message.reply_text("❌ Order not found or already processed.")
        context.user_data.clear()
        return

    # 2. DUPLICATE PROTECTION
    if waiting_for == "txid":
        c.execute(
            "SELECT order_id FROM orders WHERE txid = ? AND status != 'CANCELLED'",
            (proof,)
        )
        existing = c.fetchone()
        if existing:
            conn.close()
            await update.message.reply_text(
                f"❌ <b>Duplicate TXID Detected!</b>\n\n"
                f"This Transaction ID has already been used.\n"
                f"You cannot use the same TXID for multiple orders.\n\n"
                f"Contact support if you believe this is an error: {SUPPORT_USERNAME}",
                parse_mode=ParseMode.HTML
            )
            return
    else:  # binance_ref
        c.execute(
            "SELECT order_id FROM orders WHERE binance_ref = ? AND status != 'CANCELLED'",
            (proof,)
        )
        existing = c.fetchone()
        if existing:
            conn.close()
            await update.message.reply_text(
                f"❌ <b>Duplicate Binance Reference Detected!</b>\n\n"
                f"This payment reference has already been used.\n"
                f"You cannot reuse the same reference.\n\n"
                f"Contact support if needed: {SUPPORT_USERNAME}",
                parse_mode=ParseMode.HTML
            )
            return

    # 3. Save the proof
    if waiting_for == "txid":
        c.execute("UPDATE orders SET txid = ? WHERE order_id = ?", (proof, order_id))
        proof_type = "TXID"
    else:
        c.execute("UPDATE orders SET binance_ref = ? WHERE order_id = ?", (proof, order_id))
        proof_type = "Binance Reference"

    conn.commit()
    conn.close()

    # Clear state
    context.user_data.clear()

    # Confirm to user
    await update.message.reply_text(
        f"✅ <b>{proof_type} Submitted Successfully!</b>\n\n"
        f"🆔 Order ID: <code>{order_id}</code>\n"
        f"📄 {proof_type}: <code>{proof}</code>\n\n"
        f"Status: <b>Pending Admin Approval</b>\n"
        f"You will receive the product automatically once approved.",
        parse_mode=ParseMode.HTML
    )

    # 4. Notify Admin
    try:
        admin_text = (
            f"🔔 <b>New Payment Pending Approval</b>\n\n"
            f"🆔 Order ID: <code>{order_id}</code>\n"
            f"👤 User ID: <code>{user_id}</code>\n"
            f"💰 Amount: <b>{format_money(order['total_amount'])}</b>\n"
            f"💳 Method: <b>{order['payment_method'].upper()}</b>\n"
            f"📄 {proof_type}: <code>{proof}</code>\n\n"
            f"➡️ Go to /admin → Direct Payments"
        )
        await context.bot.send_message(
            chat_id=ADMIN_ID,
            text=admin_text,
            parse_mode=ParseMode.HTML
        )
    except Exception as e:
        logger.error(f"Failed to notify admin: {e}")


async def cancel_order(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Cancel a pending order"""
    query = update.callback_query
    await query.answer()

    try:
        order_id = query.data.split("_")[-1]
    except:
        await query.edit_message_text("❌ Invalid order.")
        return

    user_id = query.from_user.id

    conn = get_db_connection()
    c = conn.cursor()

    c.execute(
        "SELECT * FROM orders WHERE order_id = ? AND user_id = ? AND status = 'PENDING'",
        (order_id, user_id)
    )
    order = c.fetchone()

    if not order:
        conn.close()
        await query.edit_message_text("❌ Order not found or cannot be cancelled.")
        return

    c.execute(
        "UPDATE orders SET status = 'CANCELLED' WHERE order_id = ?",
        (order_id,)
    )
    conn.commit()
    conn.close()

    context.user_data.clear()

    await query.edit_message_text(
        f"❌ <b>Order Cancelled</b>\n\n"
        f"🆔 Order ID: <code>{order_id}</code>\n\n"
        f"You can create a new order anytime from the Shop.",
        parse_mode=ParseMode.HTML
    )


print("✅ Step 9 (Rewritten) completed successfully!")
print("Features included:")
print("• Submit TXID")
print("• Submit Binance Reference")
print("• Duplicate TXID protection")
print("• Duplicate Binance Reference protection")
print("• Cancel pending order")
print("• Admin notification")
print("\n➡️ Reply with 'next' to continue to Step 10 (Wallet System – Deposit)")

# ============================================
# STEP 10: Wallet System – Deposit
# ============================================

async def wallet_handler(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Show Wallet menu"""
    query = update.callback_query
    await query.answer()
    user_id = query.from_user.id

    conn = get_db_connection()
    c = conn.cursor()
    c.execute("SELECT balance FROM users WHERE user_id = ?", (user_id,))
    row = c.fetchone()
    balance = row['balance'] if row else 0.0
    conn.close()

    text = (
        f"💰 <b>Your Wallet</b>\n\n"
        f"Current Balance: <b>{format_money(balance)}</b>\n\n"
        f"You can deposit funds using BEP20 or Binance Pay."
    )

    keyboard = [
        [InlineKeyboardButton("➕ Deposit", callback_data="deposit")],
        [InlineKeyboardButton("🔙 Back to Menu", callback_data="main_menu")]
    ]

    await query.edit_message_text(
        text=text,
        reply_markup=InlineKeyboardMarkup(keyboard),
        parse_mode=ParseMode.HTML
    )


async def deposit_start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Ask for deposit amount"""
    query = update.callback_query
    await query.answer()

    context.user_data['waiting_for'] = "deposit_amount"

    text = (
        f"➕ <b>Deposit Funds</b>\n\n"
        f"Please enter the amount you want to deposit (in USD).\n\n"
        f"Example: <code>5</code> or <code>10.50</code>\n\n"
        f"Minimum recommended: $1"
    )
    keyboard = [[InlineKeyboardButton("❌ Cancel", callback_data="wallet")]]

    await query.edit_message_text(
        text=text,
        reply_markup=InlineKeyboardMarkup(keyboard),
        parse_mode=ParseMode.HTML
    )


async def handle_deposit_amount(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Receive deposit amount from user"""
    if not update.message or not update.message.text:
        return

    if context.user_data.get('waiting_for') != "deposit_amount":
        return

    try:
        amount = float(update.message.text.strip())
        if amount <= 0:
            raise ValueError
    except:
        await update.message.reply_text("❌ Invalid amount. Please send a valid number (e.g. 5 or 10.5)")
        return

    context.user_data['deposit_amount'] = amount
    context.user_data['waiting_for'] = None

    text = (
        f"💰 <b>Deposit Amount: {format_money(amount)}</b>\n\n"
        f"Select payment method:"
    )
    keyboard = [
        [InlineKeyboardButton("🪙 Pay with BEP20", callback_data="deposit_bep20")],
        [InlineKeyboardButton("🔵 Pay with Binance Pay", callback_data="deposit_binance")],
        [InlineKeyboardButton("❌ Cancel", callback_data="wallet")]
    ]

    await update.message.reply_text(
        text=text,
        reply_markup=InlineKeyboardMarkup(keyboard),
        parse_mode=ParseMode.HTML
    )


async def deposit_bep20(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Start BEP20 deposit"""
    query = update.callback_query
    await query.answer()

    amount = context.user_data.get('deposit_amount')
    if not amount:
        await query.edit_message_text("❌ Session expired.")
        return

    deposit_id = generate_deposit_id()
    context.user_data['pending_deposit_id'] = deposit_id
    context.user_data['deposit_method'] = "bep20"

    # Create pending deposit
    conn = get_db_connection()
    c = conn.cursor()
    c.execute('''
        INSERT INTO wallet_deposits (deposit_id, user_id, amount, payment_method, status, created_at)
        VALUES (?, ?, ?, ?, ?, ?)
    ''', (deposit_id, query.from_user.id, amount, "bep20", "PENDING", get_current_time()))
    conn.commit()
    conn.close()

    text = (
        f"🪙 <b>BEP20 Deposit</b>\n\n"
        f"🆔 Deposit ID: <code>{deposit_id}</code>\n"
        f"💰 Amount: <b>{format_money(amount)} USDT</b>\n\n"
        f"<b>Send exactly the amount to this address:</b>\n"
        f"<code>{BEP20_ADDRESS}</code>\n\n"
        f"Network: <b>BEP20 (BSC)</b>\n\n"
        f"After payment, click the button and submit your TXID."
    )

    keyboard = [
        [InlineKeyboardButton("✅ I Have Paid – Submit TXID", callback_data="deposit_submit_txid")],
        [InlineKeyboardButton("❌ Cancel", callback_data="wallet")]
    ]

    await query.edit_message_text(
        text=text,
        reply_markup=InlineKeyboardMarkup(keyboard),
        parse_mode=ParseMode.HTML
    )


async def deposit_binance(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Start Binance Pay deposit"""
    query = update.callback_query
    await query.answer()

    amount = context.user_data.get('deposit_amount')
    if not amount:
        await query.edit_message_text("❌ Session expired.")
        return

    deposit_id = generate_deposit_id()
    context.user_data['pending_deposit_id'] = deposit_id
    context.user_data['deposit_method'] = "binance"

    conn = get_db_connection()
    c = conn.cursor()
    c.execute('''
        INSERT INTO wallet_deposits (deposit_id, user_id, amount, payment_method, status, created_at)
        VALUES (?, ?, ?, ?, ?, ?)
    ''', (deposit_id, query.from_user.id, amount, "binance", "PENDING", get_current_time()))
    conn.commit()
    conn.close()

    text = (
        f"🔵 <b>Binance Pay Deposit</b>\n\n"
        f"🆔 Deposit ID: <code>{deposit_id}</code>\n"
        f"💰 Amount: <b>{format_money(amount)}</b>\n\n"
        f"<b>Pay to Binance ID:</b>\n"
        f"<code>{BINANCE_PAY_ID}</code>\n\n"
        f"After payment, click the button and submit your Binance Payment Reference."
    )

    keyboard = [
        [InlineKeyboardButton("✅ I Have Paid – Submit Reference", callback_data="deposit_submit_binance")],
        [InlineKeyboardButton("❌ Cancel", callback_data="wallet")]
    ]

    await query.edit_message_text(
        text=text,
        reply_markup=InlineKeyboardMarkup(keyboard),
        parse_mode=ParseMode.HTML
    )


print("✅ Step 10 completed successfully!")
print("Wallet menu + Deposit amount + BEP20/Binance deposit flow ready.")
print("\n➡️ Reply with 'next' to continue to Step 11 (Deposit Proof Submission + Duplicate Protection)")

# ============================================
# STEP 11: Deposit Proof Submission + Duplicate Protection
# ============================================

async def deposit_ask_txid(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Ask for TXID on wallet deposit"""
    query = update.callback_query
    await query.answer()

    deposit_id = context.user_data.get('pending_deposit_id')
    if not deposit_id:
        await query.edit_message_text("❌ Session expired.")
        return

    context.user_data['waiting_for'] = "deposit_txid"

    text = (
        f"📝 <b>Submit Transaction ID (TXID)</b>\n\n"
        f"🆔 Deposit ID: <code>{deposit_id}</code>\n\n"
        f"Please send your <b>BEP20 TXID</b> now."
    )
    keyboard = [[InlineKeyboardButton("❌ Cancel", callback_data="wallet")]]

    await query.edit_message_text(
        text=text,
        reply_markup=InlineKeyboardMarkup(keyboard),
        parse_mode=ParseMode.HTML
    )


async def deposit_ask_binance(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Ask for Binance reference on wallet deposit"""
    query = update.callback_query
    await query.answer()

    deposit_id = context.user_data.get('pending_deposit_id')
    if not deposit_id:
        await query.edit_message_text("❌ Session expired.")
        return

    context.user_data['waiting_for'] = "deposit_binance_ref"

    text = (
        f"📝 <b>Submit Binance Payment Reference</b>\n\n"
        f"🆔 Deposit ID: <code>{deposit_id}</code>\n\n"
        f"Please send your <b>Binance Pay Reference</b> now."
    )
    keyboard = [[InlineKeyboardButton("❌ Cancel", callback_data="wallet")]]

    await query.edit_message_text(
        text=text,
        reply_markup=InlineKeyboardMarkup(keyboard),
        parse_mode=ParseMode.HTML
    )


async def handle_deposit_proof(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Handle TXID / Binance ref for deposits + Duplicate protection"""
    if not update.message or not update.message.text:
        return

    user_id = update.effective_user.id
    proof = update.message.text.strip()
    waiting_for = context.user_data.get('waiting_for')
    deposit_id = context.user_data.get('pending_deposit_id')

    if waiting_for not in ["deposit_txid", "deposit_binance_ref"] or not deposit_id:
        return

    if len(proof) < 8:
        await update.message.reply_text("❌ Invalid proof. Please send a valid TXID or reference.")
        return

    conn = get_db_connection()
    c = conn.cursor()

    # Check deposit ownership + status
    c.execute(
        "SELECT * FROM wallet_deposits WHERE deposit_id = ? AND user_id = ? AND status = 'PENDING'",
        (deposit_id, user_id)
    )
    deposit = c.fetchone()

    if not deposit:
        conn.close()
        await update.message.reply_text("❌ Deposit not found or already processed.")
        context.user_data.clear()
        return

    # ===== DUPLICATE PROTECTION =====
    if waiting_for == "deposit_txid":
        # Check in both orders and deposits
        c.execute("SELECT deposit_id FROM wallet_deposits WHERE txid = ? AND status != 'REJECTED'", (proof,))
        if c.fetchone():
            conn.close()
            await update.message.reply_text(
                "❌ <b>Duplicate TXID detected!</b>\nThis TXID has already been used.",
                parse_mode=ParseMode.HTML
            )
            return
        c.execute("SELECT order_id FROM orders WHERE txid = ? AND status != 'CANCELLED'", (proof,))
        if c.fetchone():
            conn.close()
            await update.message.reply_text(
                "❌ <b>Duplicate TXID detected!</b>\nThis TXID has already been used in an order.",
                parse_mode=ParseMode.HTML
            )
            return
    else:
        c.execute("SELECT deposit_id FROM wallet_deposits WHERE binance_ref = ? AND status != 'REJECTED'", (proof,))
        if c.fetchone():
            conn.close()
            await update.message.reply_text(
                "❌ <b>Duplicate Binance Reference detected!</b>",
                parse_mode=ParseMode.HTML
            )
            return
        c.execute("SELECT order_id FROM orders WHERE binance_ref = ? AND status != 'CANCELLED'", (proof,))
        if c.fetchone():
            conn.close()
            await update.message.reply_text(
                "❌ <b>Duplicate Binance Reference detected!</b>",
                parse_mode=ParseMode.HTML
            )
            return

    # Save proof
    if waiting_for == "deposit_txid":
        c.execute("UPDATE wallet_deposits SET txid = ? WHERE deposit_id = ?", (proof, deposit_id))
        proof_type = "TXID"
    else:
        c.execute("UPDATE wallet_deposits SET binance_ref = ? WHERE deposit_id = ?", (proof, deposit_id))
        proof_type = "Binance Reference"

    conn.commit()
    conn.close()

    context.user_data.clear()

    await update.message.reply_text(
        f"✅ <b>{proof_type} submitted successfully!</b>\n\n"
        f"🆔 Deposit ID: <code>{deposit_id}</code>\n"
        f"📄 {proof_type}: <code>{proof}</code>\n\n"
        f"Status: <b>Pending Admin Approval</b>\n"
        f"Your balance will be credited after approval.",
        parse_mode=ParseMode.HTML
    )

    # Notify Admin
    try:
        admin_text = (
            f"💵 <b>New Wallet Deposit Pending</b>\n\n"
            f"🆔 Deposit ID: <code>{deposit_id}</code>\n"
            f"👤 User ID: <code>{user_id}</code>\n"
            f"💰 Amount: <b>{format_money(deposit['amount'])}</b>\n"
            f"💳 Method: <b>{deposit['payment_method'].upper()}</b>\n"
            f"📄 {proof_type}: <code>{proof}</code>\n\n"
            f"➡️ Go to /admin → Wallet Deposits"
        )
        await context.bot.send_message(chat_id=ADMIN_ID, text=admin_text, parse_mode=ParseMode.HTML)
    except Exception as e:
        logger.error(f"Admin notify error: {e}")


print("✅ Step 11 completed successfully!")
print("Deposit proof submission + strong duplicate protection ready.")
print("\n➡️ Reply with 'next' to continue to Step 12 (My Orders + Order History)")

# ============================================
# STEP 12: My Orders + Order History
# ============================================

async def my_orders_handler(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Show user's order history"""
    query = update.callback_query
    await query.answer()
    user_id = query.from_user.id

    conn = get_db_connection()
    c = conn.cursor()
    c.execute('''
        SELECT o.*, p.name as product_name, p.emoji
        FROM orders o
        JOIN products p ON o.product_id = p.product_id
        WHERE o.user_id = ?
        ORDER BY o.created_at DESC
        LIMIT 20
    ''', (user_id,))
    orders = c.fetchall()
    conn.close()

    if not orders:
        text = (
            f"📦 <b>My Orders</b>\n\n"
            f"You have no orders yet."
        )
        keyboard = [[InlineKeyboardButton("🔙 Back to Menu", callback_data="main_menu")]]
        await query.edit_message_text(
            text=text,
            reply_markup=InlineKeyboardMarkup(keyboard),
            parse_mode=ParseMode.HTML
        )
        return

    text = f"📦 <b>My Orders</b> (Last 20)\n\n"

    for order in orders:
        status_emoji = {
            "PENDING": "⏳",
            "APPROVED": "✅",
            "DELIVERED": "✅",
            "REJECTED": "❌",
            "CANCELLED": "🚫"
        }.get(order['status'], "❓")

        text += (
            f"{status_emoji} <b>{order['order_id']}</b>\n"
            f"{order['emoji']} {order['product_name']} × {order['quantity']}\n"
            f"💰 {format_money(order['total_amount'])} | {order['payment_method'].upper()}\n"
            f"📅 {order['created_at']}\n"
            f"Status: <b>{order['status']}</b>\n\n"
        )

    keyboard = [[InlineKeyboardButton("🔙 Back to Menu", callback_data="main_menu")]]

    # Telegram has a message length limit, so we keep it reasonable
    if len(text) > 4000:
        text = text[:3900] + "\n\n... (showing recent orders)"

    await query.edit_message_text(
        text=text,
        reply_markup=InlineKeyboardMarkup(keyboard),
        parse_mode=ParseMode.HTML
    )


print("✅ Step 12 completed successfully!")
print("My Orders / Order History ready.")
print("\n➡️ Reply with 'next' to continue to Step 13 (Admin Panel – Main Menu + Statistics)")

# ============================================
# STEP 13: Admin Panel – Main Menu + Statistics
# ============================================

async def admin_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """ /admin command – only for ADMIN_ID """
    user_id = update.effective_user.id

    if not is_admin(user_id):
        await update.message.reply_text("❌ Access denied.")
        return

    await show_admin_panel(update, context)


async def show_admin_panel(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Display Admin Main Menu"""
    text = (
        f"🛡️ <b>Veltrix Store – Admin Panel</b>\n\n"
        f"Welcome, Owner.\n"
        f"Choose an option:"
    )

    keyboard = [
        [InlineKeyboardButton("📊 Statistics", callback_data="admin_stats")],
        [
            InlineKeyboardButton("📦 Products & Stock", callback_data="admin_stock_menu"),
            InlineKeyboardButton("💳 Direct Payments", callback_data="admin_direct_payments")
        ],
        [
            InlineKeyboardButton("💵 Wallet Deposits", callback_data="admin_wallet_deposits"),
            InlineKeyboardButton("📦 Orders", callback_data="admin_orders")
        ],
        [
            InlineKeyboardButton("👥 Users", callback_data="admin_users"),
            InlineKeyboardButton("📢 Broadcast", callback_data="admin_broadcast")
        ],
        [InlineKeyboardButton("🔙 Close", callback_data="admin_close")]
    ]

    reply_markup = InlineKeyboardMarkup(keyboard)

    if update.callback_query:
        await update.callback_query.edit_message_text(
            text=text,
            reply_markup=reply_markup,
            parse_mode=ParseMode.HTML
        )
        await update.callback_query.answer()
    else:
        await update.message.reply_text(
            text=text,
            reply_markup=reply_markup,
            parse_mode=ParseMode.HTML
        )


async def admin_stats(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Show detailed statistics"""
    query = update.callback_query
    await query.answer()

    if not is_admin(query.from_user.id):
        await query.edit_message_text("❌ Access denied.")
        return

    conn = get_db_connection()
    c = conn.cursor()

    # Total users
    c.execute("SELECT COUNT(*) FROM users")
    total_users = c.fetchone()[0]

    # Total orders
    c.execute("SELECT COUNT(*) FROM orders")
    total_orders = c.fetchone()[0]

    # Pending orders
    c.execute("SELECT COUNT(*) FROM orders WHERE status = 'PENDING'")
    pending_orders = c.fetchone()[0]

    # Completed / Delivered
    c.execute("SELECT COUNT(*) FROM orders WHERE status IN ('APPROVED', 'DELIVERED')")
    completed_orders = c.fetchone()[0]

    # Rejected / Cancelled
    c.execute("SELECT COUNT(*) FROM orders WHERE status IN ('REJECTED', 'CANCELLED')")
    cancelled_orders = c.fetchone()[0]

    # Total revenue
    c.execute("SELECT COALESCE(SUM(total_amount), 0) FROM orders WHERE status IN ('APPROVED', 'DELIVERED')")
    total_revenue = c.fetchone()[0]

    # Pending wallet deposits
    c.execute("SELECT COUNT(*) FROM wallet_deposits WHERE status = 'PENDING'")
    pending_deposits = c.fetchone()[0]

    # Available stock
    c.execute("SELECT COUNT(*) FROM stock WHERE status = 'AVAILABLE'")
    available_stock = c.fetchone()[0]

    # Delivered stock
    c.execute("SELECT COUNT(*) FROM stock WHERE status = 'DELIVERED'")
    delivered_stock = c.fetchone()[0]

    conn.close()

    text = (
        f"📊 <b>Statistics – {STORE_NAME}</b>\n\n"
        f"👥 Total Users: <b>{total_users}</b>\n\n"
        f"📦 Total Orders: <b>{total_orders}</b>\n"
        f"⏳ Pending Orders: <b>{pending_orders}</b>\n"
        f"✅ Completed: <b>{completed_orders}</b>\n"
        f"❌ Cancelled/Rejected: <b>{cancelled_orders}</b>\n\n"
        f"💵 Pending Deposits: <b>{pending_deposits}</b>\n"
        f"💰 Total Revenue: <b>{format_money(total_revenue)}</b>\n\n"
        f"📦 Available Stock: <b>{available_stock}</b>\n"
        f"✅ Delivered Stock: <b>{delivered_stock}</b>"
    )

    keyboard = [[InlineKeyboardButton("🔙 Back to Admin Panel", callback_data="admin_panel")]]

    await query.edit_message_text(
        text=text,
        reply_markup=InlineKeyboardMarkup(keyboard),
        parse_mode=ParseMode.HTML
    )


async def admin_close(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Close admin panel"""
    query = update.callback_query
    await query.answer()
    await query.edit_message_text("🛡️ Admin panel closed.")


async def admin_panel_callback(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Return to admin main menu"""
    query = update.callback_query
    await query.answer()
    if not is_admin(query.from_user.id):
        await query.edit_message_text("❌ Access denied.")
        return
    await show_admin_panel(update, context)


print("✅ Step 13 completed successfully!")
print("Admin Panel main menu + full Statistics ready.")
print("\n➡️ Reply with 'next' to continue to Step 14 (Admin – Stock Management: Add Stock & Clear Stock)")

# ============================================
# STEP 14: Admin – Stock Management (Add + Clear)
# ============================================

async def admin_stock_menu(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Stock management menu"""
    query = update.callback_query
    await query.answer()

    if not is_admin(query.from_user.id):
        await query.edit_message_text("❌ Access denied.")
        return

    text = "📦 <b>Products & Stock Management</b>\n\nChoose an action:"
    keyboard = [
        [InlineKeyboardButton("📥 Add Stock", callback_data="admin_add_stock")],
        [InlineKeyboardButton("🗑️ Clear Stock", callback_data="admin_clear_stock")],
        [InlineKeyboardButton("📊 View Stock Levels", callback_data="admin_view_stock")],
        [InlineKeyboardButton("🔙 Back to Admin Panel", callback_data="admin_panel")]
    ]

    await query.edit_message_text(
        text=text,
        reply_markup=InlineKeyboardMarkup(keyboard),
        parse_mode=ParseMode.HTML
    )


async def admin_view_stock(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Show current stock levels for all products"""
    query = update.callback_query
    await query.answer()

    if not is_admin(query.from_user.id):
        return

    conn = get_db_connection()
    c = conn.cursor()
    c.execute("SELECT * FROM products ORDER BY product_id")
    products = c.fetchall()

    text = "📊 <b>Current Stock Levels</b>\n\n"

    for p in products:
        c.execute(
            "SELECT COUNT(*) FROM stock WHERE product_id = ? AND status = 'AVAILABLE'",
            (p['product_id'],)
        )
        available = c.fetchone()[0]
        c.execute(
            "SELECT COUNT(*) FROM stock WHERE product_id = ? AND status = 'DELIVERED'",
            (p['product_id'],)
        )
        delivered = c.fetchone()[0]

        text += (
            f"{p['emoji']} <b>{p['name']}</b>\n"
            f"   ✅ Available: <b>{available}</b>\n"
            f"   📤 Delivered: <b>{delivered}</b>\n\n"
        )

    conn.close()

    keyboard = [[InlineKeyboardButton("🔙 Back", callback_data="admin_stock_menu")]]
    await query.edit_message_text(text=text, reply_markup=InlineKeyboardMarkup(keyboard), parse_mode=ParseMode.HTML)


async def admin_add_stock_start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Select product to add stock"""
    query = update.callback_query
    await query.answer()

    if not is_admin(query.from_user.id):
        return

    conn = get_db_connection()
    c = conn.cursor()
    c.execute("SELECT * FROM products ORDER BY product_id")
    products = c.fetchall()
    conn.close()

    text = "📥 <b>Add Stock</b>\n\nSelect the product:"
    keyboard = []

    for p in products:
        keyboard.append([
            InlineKeyboardButton(
                f"{p['emoji']} {p['name']}",
                callback_data=f"addstock_{p['product_id']}"
            )
        ])

    keyboard.append([InlineKeyboardButton("🔙 Back", callback_data="admin_stock_menu")])

    await query.edit_message_text(text=text, reply_markup=InlineKeyboardMarkup(keyboard), parse_mode=ParseMode.HTML)


async def admin_add_stock_product(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Product selected → ask for TXT file"""
    query = update.callback_query
    await query.answer()

    if not is_admin(query.from_user.id):
        return

    product_id = int(query.data.split("_")[1])
    context.user_data['add_stock_product_id'] = product_id

    conn = get_db_connection()
    c = conn.cursor()
    c.execute("SELECT name, emoji FROM products WHERE product_id = ?", (product_id,))
    product = c.fetchone()
    conn.close()

    text = (
        f"📥 <b>Add Stock</b>\n\n"
        f"Product: {product['emoji']} <b>{product['name']}</b>\n\n"
        f"Please upload a <b>.txt</b> file.\n"
        f"One account / item per line.\n\n"
        f"Example content:\n"
        f"<code>email:pass\nemail2:pass2\ncode123</code>"
    )
    keyboard = [[InlineKeyboardButton("❌ Cancel", callback_data="admin_stock_menu")]]

    await query.edit_message_text(text=text, reply_markup=InlineKeyboardMarkup(keyboard), parse_mode=ParseMode.HTML)
    context.user_data['waiting_for'] = "stock_file"


async def handle_stock_file(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Process uploaded TXT file"""
    if not update.message or not update.message.document:
        return

    if context.user_data.get('waiting_for') != "stock_file":
        return

    if not is_admin(update.effective_user.id):
        return

    document = update.message.document

    if not document.file_name.lower().endswith(".txt"):
        await update.message.reply_text("❌ Please upload a .txt file only.")
        return

    product_id = context.user_data.get('add_stock_product_id')
    if not product_id:
        await update.message.reply_text("❌ Session expired.")
        return

    # Download file
    file = await context.bot.get_file(document.file_id)
    file_content = await file.download_as_bytearray()
    content = file_content.decode("utf-8", errors="ignore")

    lines = [line.strip() for line in content.splitlines() if line.strip()]

    if not lines:
        await update.message.reply_text("❌ File is empty.")
        return

    conn = get_db_connection()
    c = conn.cursor()

    added = 0
    for line in lines:
        c.execute(
            "INSERT INTO stock (product_id, content, status) VALUES (?, ?, 'AVAILABLE')",
            (product_id, line)
        )
        added += 1

    c.execute(
        "SELECT COUNT(*) FROM stock WHERE product_id = ? AND status = 'AVAILABLE'",
        (product_id,)
    )
    total_available = c.fetchone()[0]

    c.execute("SELECT name, emoji FROM products WHERE product_id = ?", (product_id,))
    product = c.fetchone()

    conn.commit()
    conn.close()

    context.user_data.clear()

    await update.message.reply_text(
        f"✅ <b>Stock Added Successfully!</b>\n\n"
        f"Product: {product['emoji']} <b>{product['name']}</b>\n"
        f"➕ Added: <b>{added}</b>\n"
        f"📦 Total Available now: <b>{total_available}</b>",
        parse_mode=ParseMode.HTML
    )


async def admin_clear_stock_start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Select product to clear stock"""
    query = update.callback_query
    await query.answer()

    if not is_admin(query.from_user.id):
        return

    conn = get_db_connection()
    c = conn.cursor()
    c.execute("SELECT * FROM products ORDER BY product_id")
    products = c.fetchall()
    conn.close()

    text = "🗑️ <b>Clear Stock</b>\n\nSelect the product whose AVAILABLE stock you want to clear:"
    keyboard = []

    for p in products:
        keyboard.append([
            InlineKeyboardButton(
                f"{p['emoji']} {p['name']}",
                callback_data=f"clearstock_{p['product_id']}"
            )
        ])

    keyboard.append([InlineKeyboardButton("🔙 Back", callback_data="admin_stock_menu")])

    await query.edit_message_text(text=text, reply_markup=InlineKeyboardMarkup(keyboard), parse_mode=ParseMode.HTML)


async def admin_clear_stock_confirm(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Ask confirmation before clearing"""
    query = update.callback_query
    await query.answer()

    if not is_admin(query.from_user.id):
        return

    product_id = int(query.data.split("_")[1])
    context.user_data['clear_stock_product_id'] = product_id

    conn = get_db_connection()
    c = conn.cursor()
    c.execute("SELECT name, emoji FROM products WHERE product_id = ?", (product_id,))
    product = c.fetchone()
    c.execute(
        "SELECT COUNT(*) FROM stock WHERE product_id = ? AND status = 'AVAILABLE'",
        (product_id,)
    )
    count = c.fetchone()[0]
    conn.close()

    text = (
        f"⚠️ <b>Confirm Clear Stock</b>\n\n"
        f"Product: {product['emoji']} <b>{product['name']}</b>\n"
        f"Available items that will be deleted: <b>{count}</b>\n\n"
        f"This action cannot be undone!"
    )
    keyboard = [
        [InlineKeyboardButton("✅ Yes, Clear Stock", callback_data=f"confirm_clear_{product_id}")],
        [InlineKeyboardButton("❌ No, Cancel", callback_data="admin_stock_menu")]
    ]

    await query.edit_message_text(text=text, reply_markup=InlineKeyboardMarkup(keyboard), parse_mode=ParseMode.HTML)


async def admin_clear_stock_execute(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Actually clear the stock"""
    query = update.callback_query
    await query.answer()

    if not is_admin(query.from_user.id):
        return

    product_id = int(query.data.split("_")[-1])

    conn = get_db_connection()
    c = conn.cursor()
    c.execute(
        "DELETE FROM stock WHERE product_id = ? AND status = 'AVAILABLE'",
        (product_id,)
    )
    deleted = c.rowcount
    c.execute("SELECT name, emoji FROM products WHERE product_id = ?", (product_id,))
    product = c.fetchone()
    conn.commit()
    conn.close()

    await query.edit_message_text(
        f"🗑️ <b>Stock Cleared</b>\n\n"
        f"Product: {product['emoji']} <b>{product['name']}</b>\n"
        f"Removed: <b>{deleted}</b> available items.",
        parse_mode=ParseMode.HTML
    )


print("✅ Step 14 completed successfully!")
print("Add Stock (TXT upload) + Clear Stock (with confirmation) + View Stock ready.")
print("\n➡️ Reply with 'next' to continue to Step 15 (Admin – Approve / Reject Direct Payments)")

# ============================================
# STEP 15: Admin – Approve / Reject Direct Payments + YouTube Special Message
# ============================================

async def admin_direct_payments(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """List all pending direct payments"""
    query = update.callback_query
    await query.answer()

    if not is_admin(query.from_user.id):
        await query.edit_message_text("❌ Access denied.")
        return

    conn = get_db_connection()
    c = conn.cursor()
    c.execute('''
        SELECT o.*, p.name as product_name, p.emoji, u.username, u.full_name
        FROM orders o
        JOIN products p ON o.product_id = p.product_id
        JOIN users u ON o.user_id = u.user_id
        WHERE o.status = 'PENDING' AND o.payment_method IN ('bep20', 'binance')
        ORDER BY o.created_at ASC
    ''')
    pending = c.fetchall()
    conn.close()

    if not pending:
        text = "✅ <b>No pending direct payments.</b>"
        keyboard = [[InlineKeyboardButton("🔙 Back", callback_data="admin_panel")]]
        await query.edit_message_text(text=text, reply_markup=InlineKeyboardMarkup(keyboard), parse_mode=ParseMode.HTML)
        return

    text = f"💳 <b>Pending Direct Payments</b> ({len(pending)})\n\n"

    keyboard = []
    for order in pending:
        proof = order['txid'] or order['binance_ref'] or "Not submitted"
        text += (
            f"🆔 <code>{order['order_id']}</code>\n"
            f"{order['emoji']} {order['product_name']} × {order['quantity']}\n"
            f"💰 {format_money(order['total_amount'])} | {order['payment_method'].upper()}\n"
            f"👤 {order['full_name']} (@{order['username'] or 'N/A'})\n"
            f"📄 Proof: <code>{proof}</code>\n\n"
        )
        keyboard.append([
            InlineKeyboardButton(
                f"✅ {order['order_id'][-6:]}",
                callback_data=f"approve_order_{order['order_id']}"
            ),
            InlineKeyboardButton(
                f"❌ {order['order_id'][-6:]}",
                callback_data=f"reject_order_{order['order_id']}"
            )
        ])

    keyboard.append([InlineKeyboardButton("🔙 Back to Admin Panel", callback_data="admin_panel")])

    if len(text) > 3900:
        text = text[:3800] + "\n\n... (list truncated)"

    await query.edit_message_text(
        text=text,
        reply_markup=InlineKeyboardMarkup(keyboard),
        parse_mode=ParseMode.HTML
    )


async def approve_order(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Approve a pending order and deliver stock"""
    query = update.callback_query
    await query.answer()

    if not is_admin(query.from_user.id):
        return

    order_id = query.data.replace("approve_order_", "")

    conn = get_db_connection()
    c = conn.cursor()

    # Get order
    c.execute("SELECT * FROM orders WHERE order_id = ? AND status = 'PENDING'", (order_id,))
    order = c.fetchone()

    if not order:
        conn.close()
        await query.answer("Order not found or already processed.", show_alert=True)
        return

    product_id = order['product_id']
    qty = order['quantity']
    user_id = order['user_id']

    # Check available stock
    c.execute(
        "SELECT stock_id, content FROM stock WHERE product_id = ? AND status = 'AVAILABLE' LIMIT ?",
        (product_id, qty)
    )
    stocks = c.fetchall()

    if len(stocks) < qty:
        conn.close()
        await query.answer(f"Not enough stock! Only {len(stocks)} available.", show_alert=True)
        return

    # Update order status
    c.execute(
        "UPDATE orders SET status = 'DELIVERED', approved_at = ?, delivered_at = ? WHERE order_id = ?",
        (get_current_time(), get_current_time(), order_id)
    )

    # Update user stats
    c.execute(
        "UPDATE users SET total_spent = total_spent + ?, total_orders = total_orders + 1 WHERE user_id = ?",
        (order['total_amount'], user_id)
    )

    # Mark stock as DELIVERED
    delivered_items = []
    for stock in stocks:
        c.execute(
            "UPDATE stock SET status = 'DELIVERED', reserved_by = ?, delivered_at = ?, order_id = ? WHERE stock_id = ?",
            (user_id, get_current_time(), order_id, stock['stock_id'])
        )
        delivered_items.append(stock['content'])

    # Get product info
    c.execute("SELECT name, emoji FROM products WHERE product_id = ?", (product_id,))
    product = c.fetchone()

    conn.commit()
    conn.close()

    # ========== DELIVERY LOGIC ==========
    if "YouTube" in product['name']:
        # Special message for YouTube Premium
        await send_youtube_instruction(context, order_id, user_id)
    else:
        # Normal product delivery
        delivery_text = (
            f"✅ <b>Payment Approved – Product Delivered!</b>\n\n"
            f"🆔 Order ID: <code>{order_id}</code>\n"
            f"{product['emoji']} <b>{product['name']}</b>\n"
            f"📦 Quantity: {qty}\n"
            f"💰 Amount: {format_money(order['total_amount'])}\n\n"
            f"<b>Your Product(s):</b>\n\n"
        )
        for i, item in enumerate(delivered_items, 1):
            delivery_text += f"<b>#{i}</b>\n<code>{item}</code>\n\n"

        delivery_text += "⚠️ Keep this information safe!"

        try:
            await context.bot.send_message(
                chat_id=user_id,
                text=delivery_text,
                parse_mode=ParseMode.HTML
            )
        except Exception as e:
            logger.error(f"Failed to deliver to user {user_id}: {e}")

    await query.answer("✅ Order approved & delivered!", show_alert=True)
    # Refresh the list
    await admin_direct_payments(update, context)


async def reject_order(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Reject a pending order"""
    query = update.callback_query
    await query.answer()

    if not is_admin(query.from_user.id):
        return

    order_id = query.data.replace("reject_order_", "")

    conn = get_db_connection()
    c = conn.cursor()

    c.execute("SELECT * FROM orders WHERE order_id = ? AND status = 'PENDING'", (order_id,))
    order = c.fetchone()

    if not order:
        conn.close()
        await query.answer("Order not found or already processed.", show_alert=True)
        return

    c.execute(
        "UPDATE orders SET status = 'REJECTED', approved_at = ? WHERE order_id = ?",
        (get_current_time(), order_id)
    )
    conn.commit()
    conn.close()

    # Notify user
    try:
        await context.bot.send_message(
            chat_id=order['user_id'],
            text=(
                f"❌ <b>Payment Rejected</b>\n\n"
                f"🆔 Order ID: <code>{order_id}</code>\n"
                f"Your payment could not be verified.\n"
                f"Please contact support: {SUPPORT_USERNAME}"
            ),
            parse_mode=ParseMode.HTML
        )
    except:
        pass

    await query.answer("❌ Order rejected.", show_alert=True)
    await admin_direct_payments(update, context)


print("✅ Step 15 completed successfully!")
print("Admin can now Approve / Reject direct payments + YouTube special message.")

# ============================================
# STEP 16: Admin – Approve / Reject Wallet Deposits
# ============================================

async def admin_wallet_deposits(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """List all pending wallet deposits"""
    query = update.callback_query
    await query.answer()

    if not is_admin(query.from_user.id):
        await query.edit_message_text("❌ Access denied.")
        return

    conn = get_db_connection()
    c = conn.cursor()
    c.execute('''
        SELECT d.*, u.username, u.full_name
        FROM wallet_deposits d
        JOIN users u ON d.user_id = u.user_id
        WHERE d.status = 'PENDING'
        ORDER BY d.created_at ASC
    ''')
    pending = c.fetchall()
    conn.close()

    if not pending:
        text = "✅ <b>No pending wallet deposits.</b>"
        keyboard = [[InlineKeyboardButton("🔙 Back", callback_data="admin_panel")]]
        await query.edit_message_text(text=text, reply_markup=InlineKeyboardMarkup(keyboard), parse_mode=ParseMode.HTML)
        return

    text = f"💵 <b>Pending Wallet Deposits</b> ({len(pending)})\n\n"
    keyboard = []

    for dep in pending:
        proof = dep['txid'] or dep['binance_ref'] or "Not submitted"
        text += (
            f"🆔 <code>{dep['deposit_id']}</code>\n"
            f"💰 Amount: <b>{format_money(dep['amount'])}</b>\n"
            f"💳 Method: {dep['payment_method'].upper()}\n"
            f"👤 {dep['full_name']} (@{dep['username'] or 'N/A'})\n"
            f"📄 Proof: <code>{proof}</code>\n\n"
        )
        keyboard.append([
            InlineKeyboardButton(
                f"✅ {dep['deposit_id'][-6:]}",
                callback_data=f"approve_deposit_{dep['deposit_id']}"
            ),
            InlineKeyboardButton(
                f"❌ {dep['deposit_id'][-6:]}",
                callback_data=f"reject_deposit_{dep['deposit_id']}"
            )
        ])

    keyboard.append([InlineKeyboardButton("🔙 Back to Admin Panel", callback_data="admin_panel")])

    if len(text) > 3900:
        text = text[:3800] + "\n\n... (list truncated)"

    await query.edit_message_text(
        text=text,
        reply_markup=InlineKeyboardMarkup(keyboard),
        parse_mode=ParseMode.HTML
    )


async def approve_deposit(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Approve wallet deposit and credit balance"""
    query = update.callback_query
    await query.answer()

    if not is_admin(query.from_user.id):
        return

    deposit_id = query.data.replace("approve_deposit_", "")

    conn = get_db_connection()
    c = conn.cursor()

    c.execute(
        "SELECT * FROM wallet_deposits WHERE deposit_id = ? AND status = 'PENDING'",
        (deposit_id,)
    )
    deposit = c.fetchone()

    if not deposit:
        conn.close()
        await query.answer("Deposit not found or already processed.", show_alert=True)
        return

    user_id = deposit['user_id']
    amount = deposit['amount']

    # Credit balance
    c.execute(
        "UPDATE users SET balance = balance + ? WHERE user_id = ?",
        (amount, user_id)
    )

    # Update deposit status
    c.execute(
        "UPDATE wallet_deposits SET status = 'APPROVED', approved_at = ? WHERE deposit_id = ?",
        (get_current_time(), deposit_id)
    )

    conn.commit()
    conn.close()

    # Notify user
    try:
        await context.bot.send_message(
            chat_id=user_id,
            text=(
                f"✅ <b>Deposit Approved!</b>\n\n"
                f"🆔 Deposit ID: <code>{deposit_id}</code>\n"
                f"💰 Amount credited: <b>{format_money(amount)}</b>\n\n"
                f"Your wallet balance has been updated."
            ),
            parse_mode=ParseMode.HTML
        )
    except Exception as e:
        logger.error(f"Failed to notify user {user_id}: {e}")

    await query.answer("✅ Deposit approved & balance credited!", show_alert=True)
    await admin_wallet_deposits(update, context)


async def reject_deposit(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Reject wallet deposit"""
    query = update.callback_query
    await query.answer()

    if not is_admin(query.from_user.id):
        return

    deposit_id = query.data.replace("reject_deposit_", "")

    conn = get_db_connection()
    c = conn.cursor()

    c.execute(
        "SELECT * FROM wallet_deposits WHERE deposit_id = ? AND status = 'PENDING'",
        (deposit_id,)
    )
    deposit = c.fetchone()

    if not deposit:
        conn.close()
        await query.answer("Deposit not found or already processed.", show_alert=True)
        return

    c.execute(
        "UPDATE wallet_deposits SET status = 'REJECTED', approved_at = ? WHERE deposit_id = ?",
        (get_current_time(), deposit_id)
    )
    conn.commit()
    conn.close()

    # Notify user
    try:
        await context.bot.send_message(
            chat_id=deposit['user_id'],
            text=(
                f"❌ <b>Deposit Rejected</b>\n\n"
                f"🆔 Deposit ID: <code>{deposit_id}</code>\n"
                f"Your deposit could not be verified.\n"
                f"Please contact support: {SUPPORT_USERNAME}"
            ),
            parse_mode=ParseMode.HTML
        )
    except:
        pass

    await query.answer("❌ Deposit rejected.", show_alert=True)
    await admin_wallet_deposits(update, context)


print("✅ Step 16 completed successfully!")
print("Admin can now Approve / Reject wallet deposits with automatic balance credit.")
print("\n➡️ Reply with 'next' to continue to Step 17 (Admin – Broadcast Message)")

# ============================================
# STEP 17: Admin – Broadcast Message
# ============================================

async def admin_broadcast_start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Start broadcast – ask for message"""
    query = update.callback_query
    await query.answer()

    if not is_admin(query.from_user.id):
        await query.edit_message_text("❌ Access denied.")
        return

    context.user_data['waiting_for'] = "broadcast_message"

    text = (
        f"📢 <b>Broadcast Message</b>\n\n"
        f"Please send the message you want to broadcast to all users.\n\n"
        f"You can use HTML formatting:\n"
        f"• <code>&lt;b&gt;bold&lt;/b&gt;</code>\n"
        f"• <code>&lt;i&gt;italic&lt;/i&gt;</code>\n"
        f"• <code>&lt;code&gt;copyable&lt;/code&gt;</code>\n\n"
        f"Send your message now:"
    )
    keyboard = [[InlineKeyboardButton("❌ Cancel", callback_data="admin_panel")]]

    await query.edit_message_text(
        text=text,
        reply_markup=InlineKeyboardMarkup(keyboard),
        parse_mode=ParseMode.HTML
    )


async def handle_broadcast_message(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Receive broadcast message and show preview"""
    if not update.message or not update.message.text:
        return

    if context.user_data.get('waiting_for') != "broadcast_message":
        return

    if not is_admin(update.effective_user.id):
        return

    message = update.message.text
    context.user_data['broadcast_text'] = message
    context.user_data['waiting_for'] = None

    # Count users
    conn = get_db_connection()
    c = conn.cursor()
    c.execute("SELECT COUNT(*) FROM users")
    total_users = c.fetchone()[0]
    conn.close()

    preview = (
        f"📢 <b>Broadcast Preview</b>\n\n"
        f"Message:\n"
        f"{message}\n\n"
        f"Will be sent to approximately <b>{total_users}</b> users.\n\n"
        f"Do you want to send it?"
    )

    keyboard = [
        [InlineKeyboardButton("✅ Yes, Send Now", callback_data="broadcast_confirm")],
        [InlineKeyboardButton("❌ Cancel", callback_data="admin_panel")]
    ]

    await update.message.reply_text(
        text=preview,
        reply_markup=InlineKeyboardMarkup(keyboard),
        parse_mode=ParseMode.HTML
    )


async def broadcast_confirm(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Send the broadcast to all users"""
    query = update.callback_query
    await query.answer()

    if not is_admin(query.from_user.id):
        return

    message = context.user_data.get('broadcast_text')
    if not message:
        await query.edit_message_text("❌ No message found. Please start again.")
        return

    await query.edit_message_text("📤 Sending broadcast... Please wait.")

    conn = get_db_connection()
    c = conn.cursor()
    c.execute("SELECT user_id FROM users")
    users = c.fetchall()
    conn.close()

    success = 0
    failed = 0

    for user in users:
        try:
            await context.bot.send_message(
                chat_id=user['user_id'],
                text=message,
                parse_mode=ParseMode.HTML
            )
            success += 1
            await asyncio.sleep(0.05)  # small delay to avoid flood limits
        except Exception:
            failed += 1

    context.user_data.clear()

    result_text = (
        f"✅ <b>Broadcast Completed</b>\n\n"
        f"📤 Successfully sent: <b>{success}</b>\n"
        f"❌ Failed: <b>{failed}</b>\n\n"
        f"Total attempted: <b>{success + failed}</b>"
    )

    keyboard = [[InlineKeyboardButton("🔙 Back to Admin Panel", callback_data="admin_panel")]]

    await query.edit_message_text(
        text=result_text,
        reply_markup=InlineKeyboardMarkup(keyboard),
        parse_mode=ParseMode.HTML
    )


print("✅ Step 17 completed successfully!")
print("Broadcast feature with preview + confirmation ready.")
print("\n➡️ Reply with 'next' to continue to Step 18 (Register all Handlers + Final Run Cell)")

# ============================================
# FIXED TEXT HANDLER + RESTART
# ============================================

async def unified_text_handler(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """One smart handler that routes messages based on current state"""
    if not update.message or not update.message.text:
        return

    waiting_for = context.user_data.get('waiting_for')

    # 1. Deposit Amount
    if waiting_for == "deposit_amount":
        await handle_deposit_amount(update, context)
        return

    # 2. Order TXID / Binance Ref
    if waiting_for in ["txid", "binance_ref"]:
        await handle_payment_proof(update, context)
        return

    # 3. Deposit TXID / Binance Ref
    if waiting_for in ["deposit_txid", "deposit_binance_ref"]:
        await handle_deposit_proof(update, context)
        return

    # 4. Broadcast message
    if waiting_for == "broadcast_message":
        await handle_broadcast_message(update, context)
        return


# Clear and re-register everything properly
application.handlers.clear()

# Commands
application.add_handler(CommandHandler("start", start_command))
application.add_handler(CommandHandler("admin", admin_command))

# Force Join
application.add_handler(CallbackQueryHandler(check_membership_callback, pattern="^check_membership$"))

# Main Menu
application.add_handler(CallbackQueryHandler(main_menu_callback, pattern="^main_menu$"))
application.add_handler(CallbackQueryHandler(shop_handler, pattern="^shop$"))
application.add_handler(CallbackQueryHandler(profile_handler, pattern="^profile$"))
application.add_handler(CallbackQueryHandler(wallet_handler, pattern="^wallet$"))
application.add_handler(CallbackQueryHandler(my_orders_handler, pattern="^my_orders$"))
application.add_handler(CallbackQueryHandler(support_handler, pattern="^support$"))
application.add_handler(CallbackQueryHandler(terms_handler, pattern="^terms$"))

# Shop
application.add_handler(CallbackQueryHandler(product_selected, pattern="^product_"))
application.add_handler(CallbackQueryHandler(quantity_selected, pattern="^qty_"))

# Payments
application.add_handler(CallbackQueryHandler(pay_from_wallet, pattern="^pay_wallet$"))
application.add_handler(CallbackQueryHandler(pay_bep20, pattern="^pay_bep20$"))
application.add_handler(CallbackQueryHandler(pay_binance, pattern="^pay_binance$"))
application.add_handler(CallbackQueryHandler(ask_txid, pattern="^submit_txid$"))
application.add_handler(CallbackQueryHandler(ask_binance_ref, pattern="^submit_binance_ref$"))
application.add_handler(CallbackQueryHandler(cancel_order, pattern="^cancel_order_"))

# Wallet Deposit
application.add_handler(CallbackQueryHandler(deposit_start, pattern="^deposit$"))
application.add_handler(CallbackQueryHandler(deposit_bep20, pattern="^deposit_bep20$"))
application.add_handler(CallbackQueryHandler(deposit_binance, pattern="^deposit_binance$"))
application.add_handler(CallbackQueryHandler(deposit_ask_txid, pattern="^deposit_submit_txid$"))
application.add_handler(CallbackQueryHandler(deposit_ask_binance, pattern="^deposit_submit_binance$"))

# Admin
application.add_handler(CallbackQueryHandler(admin_panel_callback, pattern="^admin_panel$"))
application.add_handler(CallbackQueryHandler(admin_stats, pattern="^admin_stats$"))
application.add_handler(CallbackQueryHandler(admin_close, pattern="^admin_close$"))
application.add_handler(CallbackQueryHandler(admin_stock_menu, pattern="^admin_stock_menu$"))
application.add_handler(CallbackQueryHandler(admin_view_stock, pattern="^admin_view_stock$"))
application.add_handler(CallbackQueryHandler(admin_add_stock_start, pattern="^admin_add_stock$"))
application.add_handler(CallbackQueryHandler(admin_add_stock_product, pattern="^addstock_"))
application.add_handler(CallbackQueryHandler(admin_clear_stock_start, pattern="^admin_clear_stock$"))
application.add_handler(CallbackQueryHandler(admin_clear_stock_confirm, pattern="^clearstock_"))
application.add_handler(CallbackQueryHandler(admin_clear_stock_execute, pattern="^confirm_clear_"))
application.add_handler(CallbackQueryHandler(admin_direct_payments, pattern="^admin_direct_payments$"))
application.add_handler(CallbackQueryHandler(approve_order, pattern="^approve_order_"))
application.add_handler(CallbackQueryHandler(reject_order, pattern="^reject_order_"))
application.add_handler(CallbackQueryHandler(admin_wallet_deposits, pattern="^admin_wallet_deposits$"))
application.add_handler(CallbackQueryHandler(approve_deposit, pattern="^approve_deposit_"))
application.add_handler(CallbackQueryHandler(reject_deposit, pattern="^reject_deposit_"))
application.add_handler(CallbackQueryHandler(admin_broadcast_start, pattern="^admin_broadcast$"))
application.add_handler(CallbackQueryHandler(broadcast_confirm, pattern="^broadcast_confirm$"))

# Document (for stock upload)
application.add_handler(MessageHandler(filters.Document.ALL, handle_stock_file))

# Unified text handler (this fixes the deposit problem)
application.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, unified_text_handler))

print("✅ Fixed handlers registered!")
print("🚀 Starting bot...")

application.run_polling(drop_pending_updates=True)

# ============================================
# ADD MISSING ADMIN: ORDERS + USERS
# ============================================

async def admin_orders(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Show recent orders in admin panel"""
    query = update.callback_query
    await query.answer()

    if not is_admin(query.from_user.id):
        await query.edit_message_text("❌ Access denied.")
        return

    conn = get_db_connection()
    c = conn.cursor()
    c.execute('''
        SELECT o.*, p.name as product_name, p.emoji, u.username, u.full_name
        FROM orders o
        JOIN products p ON o.product_id = p.product_id
        JOIN users u ON o.user_id = u.user_id
        ORDER BY o.created_at DESC
        LIMIT 15
    ''')
    orders = c.fetchall()
    conn.close()

    if not orders:
        text = "📦 <b>Orders</b>\n\nNo orders yet."
    else:
        text = f"📦 <b>Recent Orders</b> (Last 15)\n\n"
        for o in orders:
            status_emoji = {
                "PENDING": "⏳",
                "APPROVED": "✅",
                "DELIVERED": "✅",
                "REJECTED": "❌",
                "CANCELLED": "🚫"
            }.get(o['status'], "❓")

            text += (
                f"{status_emoji} <code>{o['order_id']}</code>\n"
                f"{o['emoji']} {o['product_name']} × {o['quantity']}\n"
                f"💰 {format_money(o['total_amount'])} | {o['payment_method'].upper()}\n"
                f"👤 {o['full_name']} (@{o['username'] or 'N/A'})\n"
                f"Status: <b>{o['status']}</b>\n\n"
            )

    if len(text) > 4000:
        text = text[:3900] + "\n\n... (truncated)"

    keyboard = [[InlineKeyboardButton("🔙 Back to Admin Panel", callback_data="admin_panel")]]
    await query.edit_message_text(text=text, reply_markup=InlineKeyboardMarkup(keyboard), parse_mode=ParseMode.HTML)


async def admin_users(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Show users list in admin panel"""
    query = update.callback_query
    await query.answer()

    if not is_admin(query.from_user.id):
        await query.edit_message_text("❌ Access denied.")
        return

    conn = get_db_connection()
    c = conn.cursor()
    c.execute('''
        SELECT user_id, username, full_name, balance, total_spent, total_orders, joined_at
        FROM users
        ORDER BY joined_at DESC
        LIMIT 20
    ''')
    users = c.fetchall()
    conn.close()

    if not users:
        text = "👥 <b>Users</b>\n\nNo users yet."
    else:
        text = f"👥 <b>Users</b> (Last 20)\n\n"
        for u in users:
            text += (
                f"👤 <b>{u['full_name'] or 'N/A'}</b> (@{u['username'] or 'None'})\n"
                f"🆔 <code>{u['user_id']}</code>\n"
                f"💰 Balance: {format_money(u['balance'])} | Spent: {format_money(u['total_spent'])}\n"
                f"📦 Orders: {u['total_orders']} | Joined: {u['joined_at']}\n\n"
            )

    if len(text) > 4000:
        text = text[:3900] + "\n\n... (truncated)"

    keyboard = [[InlineKeyboardButton("🔙 Back to Admin Panel", callback_data="admin_panel")]]
    await query.edit_message_text(text=text, reply_markup=InlineKeyboardMarkup(keyboard), parse_mode=ParseMode.HTML)


# Re-register the two missing handlers + restart
application.add_handler(CallbackQueryHandler(admin_orders, pattern="^admin_orders$"))
application.add_handler(CallbackQueryHandler(admin_users, pattern="^admin_users$"))

print("✅ Orders and Users buttons added!")
print("You can now use them without restarting (or restart if you want).")

with open("requirements.txt", "w") as f:
    f.write("python-telegram-bot==21.6\n")

print("✅ requirements.txt created successfully!")

with open("Procfile", "w") as f:
    f.write("worker: python main.py\n")   # Change main.py if your file has different name

print("✅ Procfile created successfully!")